services:
  api:
    image: ghcr.io/maede97/Rega-eINK-server:latest
    build:
      context: .
      dockerfile: Dockerfile
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]
    ports:
      - "8000:8000"
    volumes:
      - ./flights.db:/app/flights.db
    restart: unless-stopped

  fetcher:
    image: ghcr.io/maede97/Rega-eINK-server:latest
    build:
      context: .
      dockerfile: Dockerfile
    command: ["python", "fetch_current_data.py"]
    volumes:
      - ./flights.db:/app/flights.db
    restart: no